##-------------------------
## general information
##-------------------------

baseURL = 'http://lectore.com/'


##-------------------------
## directory config
##-------------------------
contentDir = "plates"



##-------------------------
## themes overide
##-------------------------
# themesDir  = "library/theme/" 
# theme  = []                                   


##-------------------------
## language config
##-------------------------

defaultContentLanguage = 'id'


##-------------------------
## site configs
##-------------------------

paginate                   = 20                   # site pagination
disableKinds               = [ "taxonomy" ]       # disable kind
disableHugoGeneratorInject = true                 # disable injection


##-------------------------
## site taxonomies
##-------------------------

[taxonomies]
    category  = "categories"
    tag       = "tags"
    docus     = "docus"
    event     = "events"
    tutorial  = "tutorials"
    canal     = "canals"
    course    = "courses"
    project   = "projects"
    report    = "reports"
    position  = "positions"
    topic     = "topics"


##-------------------------
## output format
##-------------------------

[outputs]
    home = ['HTML']


##-------------------------
## build configs
##-------------------------

[build]
    noJSConfigInAssets = true