##-------------------------
## general information
##-------------------------

baseURL = 'http://lectore.com/'



##-------------------------
## plugins and themes
##-------------------------

theme = []                                   



##-------------------------
## language config
##-------------------------

defaultContentLanguage = 'id'



##-------------------------
## site taxonomies
##-------------------------

[taxonomies]
    category  = "categories"
    tag       = "tags"
    docus     = "docus"
    event     = "events"
    tutorial  = "tutorials"
    canal     = "canals"
    course    = "courses"
    project   = "projects"
    report    = "reports"
    position  = "positions"
    topic     = "topics"



##-------------------------
## site configs
##-------------------------

paginate                   = 20                   # site pagination
disableKinds               = [ "taxonomy" ]       # disable kind
disableHugoGeneratorInject = true                 # disable injection



##-------------------------
## custom outputs
##-------------------------
#
# [outputs]
#   home = ["HTML", "RSS", "JSON"]



##-------------------------
## custom directory
##-------------------------

[module]
[[module.mounts]]
    source = 'module/format'
    target = 'archetypes'
[[module.mounts]]
    source = 'module/layouts'
    target = 'layouts'
[[module.mounts]]
    source = 'module/langua'
    target = 'i18n'
[[module.mounts]]
    source = 'assets'
    target = 'assets'
[[module.mounts]]
    source = 'assets'
    target = 'static'
[[module.mounts]]
    source = 'datums'
    target = 'data'
