##-------------------------
## general information
##-------------------------

baseURL = 'http://lectore.com/'



##-------------------------
## themes overide
##-------------------------
themesDir  = "library/theme/" 
theme  = []                                   


##-------------------------
## language config
##-------------------------

defaultContentLanguage = 'id'


##-------------------------
## site configs
##-------------------------

paginate                   = 20                   # site pagination
disableKinds               = [ "taxonomy" ]       # disable kind
disableHugoGeneratorInject = true                 # disable injection


##-------------------------
## site taxonomies
##-------------------------

[taxonomies]
    category  = "categories"
    tag       = "tags"
    docus     = "docus"
    event     = "events"
    tutorial  = "tutorials"
    canal     = "canals"
    course    = "courses"
    project   = "projects"
    report    = "reports"
    position  = "positions"
    topic     = "topics"


##-------------------------
## output format
##-------------------------

[outputs]
    home = ['HTML']


##-------------------------
## build configs
##-------------------------

[build]
    noJSConfigInAssets = true



##-------------------------
## directory config
##-------------------------

contentDir = "datum"
publishDir = "sites"

[module]
[[module.mounts]]
    source = 'library/format'
    target = 'archetypes'
[[module.mounts]]
    source = 'library/layouts'
    target = 'layouts'
[[module.mounts]]
    source = 'library/auxiler'
    target = 'layouts/auxiler'
[[module.mounts]]
    source = 'library/langua'
    target = 'i18n'
[[module.mounts]]
    source = 'library/scripts'
    target = 'assets'
[[module.mounts]]
    source = 'library/styles'
    target = 'assets/styles'
[[module.mounts]]
    source = 'library/shapes/fonts'
    target = 'assets'
[[module.mounts]]
    source = 'library/shapes/anim'
    target = 'assets'
[[module.mounts]]
    source = 'library/shapes/icons'
    target = 'assets'
[[module.mounts]]
    source = 'assets'
    target = 'static'
[[module.mounts]]
    source = 'assets/docus'
    target = 'data'