##-------------------------
## general information
##-------------------------

baseURL = 'http://lectore.com/'


##-------------------------
## directory config
##-------------------------

contentDir = "master/content/"
themesDir  = "module/plugins/"  
publishDir = "publish"


##-------------------------
## register plugins
##-------------------------

theme  = [ "based" ]                                   


##-------------------------
## language config
##-------------------------

defaultContentLanguage = 'id'


##-------------------------
## site configs
##-------------------------

paginate                   = 20                   # site pagination
disableKinds               = [ "taxonomy" ]       # disable kind
disableHugoGeneratorInject = true                 # disable injection


##-------------------------
## site taxonomies
##-------------------------

[taxonomies]
    category  = "categories"
    tag       = "tags"
    docus     = "docus"
    event     = "events"
    tutorial  = "tutorials"
    canal     = "canals"
    course    = "courses"
    project   = "projects"
    report    = "reports"
    position  = "positions"
    topic     = "topics"


##-------------------------
## output format
##-------------------------

[outputs]
    home = ['HTML']

##-------------------------
## module config
##-------------------------


[module]
[[module.mounts]]
    source = 'module/format'
    target = 'archetypes'
[[module.mounts]]
    source = 'module/layouts'
    target = 'layouts'
[[module.mounts]]
    source = 'module/langua'
    target = 'i18n'
[[module.mounts]]
    source = 'assets'
    target = 'static'
[[module.mounts]]
    source = 'master/datums'
    target = 'data'