##-------------------------
## sitest permalinks
##-------------------------

baseURL = 'http://lectore.com/'



##-------------------------
## language configuration
##-------------------------

defaultContentLanguage = 'id'

