[id]
    weight = 1
    title = "karim id"
    languageCode= "id"
    contentDir = "content/sites/id"
    languageName = "Bahasa"
[en]
    weight = 2
    title = "Karim en"
    languageCode= "en"
    contentDir = "content/sites/en"
    languageName = "English"