[id]
    weight = 1
    title = "karim id"
    languageCode= "id"
    contentDir = "content/page/id"
    languageName = "Bahasa"

[en]
    weight = 2
    title = "Karim en"
    languageCode= "en"
    contentDir = "content/page/en"
    languageName = "English"