## -----------------------
##  IMPORT MODULE
## -----------------------

## ---- Import rozarder : Icons, fonts, animation, script and styles framework 

[[imports]]
    path = "github.com/rozard-falcon/colorize"


[[imports]]
    path = "github.com/rozard-falcon/robicons"



## -----------------------
##  REBASED STRUCTURE
## -----------------------


## ---- rebased archetypes directory

[[mounts]]
    source = 'library/format'
    target = 'archetypes'


## ----- rebased layouts directory

[[mounts]]
    source = 'library/render'
    target = 'layouts'
[[mounts]]
    source = 'library/render'
    target = 'layouts/partials'
[[mounts]]
    source = 'library/render/_cores'
    target = 'layouts/_default'
[[mounts]]
    source = 'library/render/_cores/core.html'
    target = 'layouts/_default/baseof.html'
[[mounts]]
    source = 'library/render/_cores/listing.html'
    target = 'layouts/_default/list.html'
[[mounts]]
    source = 'library/render/paged'
    target = 'layouts/_default'
[[mounts]]
    source = 'library/auxile'
    target = 'layouts/partials/bin'
[[mounts]]
    source = 'library/render/blocks'
    target = 'layouts/shortcodes'
[[mounts]]
    source = 'library/render/modul'
    target = 'static/modul'


## ---- rebase languange directory
[[mounts]]
    source = 'library/langua'
    target = 'i18n'


## ---- rebase static directory
[[mounts]]
    source = 'library/statics'
    target = 'static'


## ---- rebase data directory 
[[mounts]]
    source = 'assets/datums'
    target = 'data'