## -----------------------
##  IMPORT MODULE
## -----------------------

## ---- Import rozarder : Icons, fonts, animation, script and styles framework 


## -----------------------
##  based directory
## -----------------------

[[mounts]]
    source = 'based'
    target = 'layouts/_default'

[[mounts]]
    source = 'based/recore.html'
    target = 'layouts/_default/baseof.html'

[[mounts]]
    source = 'based/single.html'
    target = 'layouts/_default/single.html'

[[mounts]]
    source = 'based/listing.html'
    target = 'layouts/_default/list.html'



## -----------------------
##  based directory
## -----------------------



## ---- rebased archetypes directory

[[mounts]]
    source = 'format'
    target = 'archetypes'


## ----- rebased layouts directory

[[mounts]]
    source = 'render'
    target = 'layouts'
[[mounts]]
    source = 'global'
    target = 'layouts/partials'
[[mounts]]
    source = 'render/paged'
    target = 'layouts'
[[mounts]]
    source = 'auxile'
    target = 'layouts/partials/bin'
[[mounts]]
    source = 'render/blocks'
    target = 'layouts/shortcodes'
[[mounts]]
    source = 'render/modul'
    target = 'static/modul'



## ---- rebase languange directory
[[mounts]]
    source = 'langua'
    target = 'i18n'


## ---- rebase static directory
[[mounts]]
    source = 'source'
    target = 'static'


## ---- rebase data directory 
[[mounts]]
    source = 'assets/media/docus'
    target = 'data'



## --------------------
## Rebase partials
## --------------------


[[mounts]]
    source = 'global'
    target = 'layouts/partials'

[[mounts]]
    source = 'auxile'
    target = 'layouts/partials/bin'

[[mounts]]
    source = 'engine'
    target = 'layouts/partials/colorize'

[[mounts]]
    source = 'assets'
    target = 'assets/colorize/'

[[mounts]]
    source = 'source'
    target = 'static/colorize/'