## -----------------------
##  assets directory
## -----------------------

[[mounts]]
    source = 'assets'
    target = 'assets/recores'



## -----------------------
##  library directory
## -----------------------

[[mounts]]
    source = 'library/format'
    target = 'archetypes'

[[mounts]]
    source = 'library/interns'
    target = 'layouts/partials/recores/interns'


[[mounts]]
    source = 'library/globals'
    target = 'layouts/partials'


[[mounts]]
    source = 'library/langua'
    target = 'i18n'


## -----------------------
##  render directory
## -----------------------

[[mounts]]
    source = 'render/based/baseof.html'
    target = 'layouts/_default/baseof.html'


[[mounts]]
    source = 'render/metadata'
    target = 'layouts/partials/metadata'

[[mounts]]
    source = 'render/analytical'
    target = 'layouts/partials/analytical'


## -----------------------
##  module directory
## -----------------------

[[mounts]]
    source = 'module'
    target = 'static'


## -----------------------
##  datum directory
## -----------------------

[[mounts]]
    source = 'source/datum'
    target = 'data'

[[mounts]]
    source = 'source/media/anima'
    target = 'assets/anima'

[[mounts]]
    source = 'source/media/audio'
    target = 'assets/audio'

[[mounts]]
    source = 'source/media/image'
    target = 'assets/video'

[[mounts]]
    source = 'source/media/video'
    target = 'assets/video'