## -----------------------
##  IMPORT MODULE
## -----------------------

## ---- Import rozarder : Icons, fonts, animation, script and styles framework 

[[imports]]
    path = "github.com/rozard-falcon/colorize"


## -----------------------
##  REBASED STRUCTURE
## -----------------------



## --------------------
## Rebase _default
## --------------------

[[mounts]]
    source = 'library/render/based'
    target = 'layouts/_default'

[[mounts]]
    source = 'library/render/based/recore.html'
    target = 'layouts/_default/baseof.html'

[[mounts]]
    source = 'library/render/based/single.html'
    target = 'layouts/_default/single.html'

[[mounts]]
    source = 'library/render/based/listing.html'
    target = 'layouts/_default/list.html'



## ---- rebased archetypes directory

[[mounts]]
    source = 'library/format'
    target = 'archetypes'


## ----- rebased layouts directory

[[mounts]]
    source = 'library/render'
    target = 'layouts'
[[mounts]]
    source = 'library/render'
    target = 'layouts/partials'
[[mounts]]
    source = 'library/render/paged'
    target = 'layouts/rebase'
[[mounts]]
    source = 'library/auxile'
    target = 'layouts/partials/bin'
[[mounts]]
    source = 'library/render/blocks'
    target = 'layouts/shortcodes'
[[mounts]]
    source = 'library/render/modul'
    target = 'static/modul'



## ---- rebase languange directory
[[mounts]]
    source = 'library/langua'
    target = 'i18n'


## ---- rebase static directory
[[mounts]]
    source = 'library/statics'
    target = 'static'


## ---- rebase data directory 
[[mounts]]
    source = 'assets/media/docus'
    target = 'data'