description = 'Text about my cool site'             # site description
images      = ['images/sample.jpg']                 # site default images


[site_meta]
    leads      = ""                                 # site tagline
    author     = ""                                 # Default author name  
    logo_light = ""                                 # site logo light (path/url)
    logo_darks = ""                                 # site logo dark (path/url)


[base_model]
    logos    = "icon"                               # icon, text, all
    helps    = "icon"                               # icon, text, both, menu 
    header   = "based"                              # footer model
    footer   = "based"                              # header model
    nopage   = "based"                              # 404 page not found


[contact]
    phone      = "test phone"                       # phone number
    email      = "test mail"                        # contact email
    address1   = "Office main address"              # office primary address
    address2   = "Office secondary address"         # office secondary address
    telegram   = "@null"                            # telegram group
    whatsapp   = "+62-895-0765-1345"                # whatsapp contact person
    postaddr   = ""                                 # Mailing address or mailing address


[social]
    facebook  = "my facebook id"                    # facebook username
    twitter   = "my twitter id"                     # twitter username
    instagram = "my instagram id"                   # instagram username
    tiktok    = "my tiktok id"                      # tiktok username
    youtube   = "my youtube id"                     # youtube chanel
    discord   = "my discord id"                     # discord id


[workspace] 
    github    = "my github account"                 # github account
    gitlab    = "my gilab account"                  # gitlab username
    jira      = "my jira account"                   # jira workspace
    slack     = "my slack account"                  # slack account


[features]
    darkmode = true   # true, false                 # enable darkmode
    pwa_apps = false  # true, false                 # enable progresive web application
   

[searchs]
    status = true     # true, false
    engine = "self"   # algolia, fuse               # search engine  
    [algolia]
        unique = "algolia_id"                       # algolia unique id
        secret = "algolia_secret"                   # algolia secret key