# MAIN METADATA
description = 'Text about my cool site'             # site description
images      = ['images/sample.jpg']                 # site default images



# SITE METADATA
[site_meta]
    leads      = ""                                 # site tagline
    author     = ""                                 # Default author name  
    logo_light = ""                                 # site logo light (path/url)
    logo_darks = ""                                 # site logo dark (path/url)


[base_model]
    logos    = "icon"                               # icon, text, all
    helps    = "icon"                               # icon, text, both, menu 
    header   = "based"                              # footer model
    footer   = "based"                              # header model
    nopage   = "based"                              # 404 page not found


[contact]
    phone      = "test phone"                       # phone number
    email      = "test mail"                        # contact email
    address1   = "Office main address"              # office primary address
    address2   = "Office secondary address"         # office secondary address
    telegram   = "@null"                            # telegram group
    whatsapp   = "+62-895-0765-1345"                # whatsapp contact person
    postaddr   = ""                                 # Mailing address or mailing address


[social]
    facebook  = "my facebook id"                    # facebook username
    twitter   = "my twitter id"                     # twitter username
    instagram = "my instagram id"                   # instagram username
    tiktok    = "my tiktok id"                      # tiktok username
    youtube   = "my youtube id"                     # youtube chanel id
    discord   = "my discord id"                     # discord id


[workspace] 
    github    = "github account"                    # github account
    gitlab    = "gilab account"                     # gitlab username
    jira      = "jira account"                      # jira workspace
    slack     = "slack account"                     # slack account