[recores]
    [recores.assets]
        [recores.assets.styles]
            head = [ "base", "cols", "link",  "space", "text", "utils" ]
            foot = [ "base", "code", "form", "list", "table", "utils" ]
        [recores.assets.script]
            head = [ "base" ]
            foot = [ "base" ]