[site_meta]
    leads      = ""                                 # site tagline
    descs      = "site description"                 # site description
    phone      = "test phone"                       # phone number
    email      = "test mail"                        # contact email
    address1   = "Office main address"              # office primary address
    address2   = "Office secondary address"         # office secondary address
    telegram   = "@null"                            # telegram group
    whatsapp   = "+62-895-0765-1345"                # whatsapp contact person
    postaddr   = ""                                 # Mailing address or mailing address
    author     = ""                                 # Default author name  
    logo_light = ""                                 # site logo light (path/url)
    logo_darks = ""                                 # site logo dark (path/url)


[base_model]
    logos    = "icon"                                # icon, text, all
    helps    = "menu"                               # icon, text, both, menu 
    header   = "base"                               # footer model
    footer   = "base"                               # header model
    nopage   = "base"                               # 404 page not found


[social_media]
    facebook  = "my facebook id"                    # facebook username
    twitter   = "my twitter id"                     # twitter username
    instagram = "my instagram id"                   # instagram username
    tiktok    = "my tiktok id"                      # tiktok username
    youtube   = "my youtube id"                     # youtube chanel
    discord   = "my discord id"                     # discord id


[workspace] 
    github    = "my github account"                 # github account
    gitlab    = "my gilab account"                  # gitlab username
    jira      = "my jira account"                   # jira workspace
    slack     = "my slack account"                  # slack account


[features]
    darkmode = true   # true, false                 # enable darkmode
    search   = true   # fusejs, algolia             # enable search features


[services]
    [algolia]
        unique = "algolia_id"                       # algolia unique id
        secret = "algolia_secret"                   # algolia secret key
    [disqus]
        unique = "disqus_id"                        # disqus unique id
        secret = "disqus_secret"                    # disqus secret
    [youtube]   
        unique = "youtube_id"                       # youtube unique id
        secret = "youtube_secret"                   # youtube secret 