[recores]
    [recores.assets]
        [recores.assets.styles]
            head = [ "base", "cols", "link", "text", "utils" ]
            foot = [ "base", "code", "cols","form", "list", "space", "table", "text", "utils" ]
        [recores.assets.script]
            head = [ "base" ]
            foot = [ "base" ]