[recores]
    [recores.assets]
        [recores.assets.styles]
            head = [ "base", "cols", "flex", "form", "grid", "icon", "link", "list", "space", "table", "tabs", "text", "utils" ]
            foot = [ "base", "audio", "code", "cols", "flex", "form", "grid", "icon", "iframe", "image",  "link", "list", "space", "table", "tabs", "text", "utils", "video" ]
        [recores.assets.script]
            head = [ "base" ]
            foot = [ "base" ]
 
