[recores]
    [recores.assets]
        [recores.assets.styles]
            head = [ "main", "cols", "link", "space", "text", "utils" ]
            foot = [ "main", "cols", "code", "form", "list", "table", "utils" ]
        [recores.assets.script]
            head = [ "main" ]
            foot = [ "main" ]