
##-------------------------
## custom outputs
##-------------------------
#
# [outputs]
#   home = ["HTML", "RSS", "JSON"]

##-------------------------
## minify outputs
##-------------------------

[minify]
    disableCSS   = false
    disableHTML  = false
    disableJS    = false
    disableJSON  = false
    disableSVG   = false
    disableXML   = false
    minifyOutput = true
    [minify.tdewolff]
        [minify.tdewolff.css]
            keepCSS2 = true
            precision = 0
        [minify.tdewolff.html]
            keepComments = false
            keepConditionalComments = false
            keepDefaultAttrVals = true
            keepDocumentTags = true
            keepEndTags = true
            keepQuotes = true
            keepWhitespace = false
        [minify.tdewolff.js]
            keepVarNames = false
            precision = 0
            version = 2022
        [minify.tdewolff.json]
            keepNumbers = false
            precision = 0
        [minify.tdewolff.svg]
            keepComments = false
            precision = 0
        [minify.tdewolff.xml]
            keepWhitespace = false
